In [1]:
import pandas as pd

df=pd.read_csv('user_contrib.csv')
df[:10]

,author,subreddit,month,year,num_posts,avg_upvote,num_replies
0,--DrScience--,dataisugly,3,2017,1.0,0.99,NaN
1,-100-Broken-Windows-,dataisugly,2,2015,1.0,0.97,NaN
2,-Abradolf_Lincler-,dataisugly,12,2019,1.0,1.00,NaN
3,-Canonical-,dataisugly,3,2017,1.0,0.98,NaN
4,-ComputerCat-,visualization,6,2019,1.0,0.96,NaN
5,-Mikee,dataisugly,2,2021,NaN,NaN,2.0
6,-SkarchieBonkers-,visualization,1,2021,NaN,NaN,4.0
7,-bmg-,dataisugly,1,2021,NaN,NaN,2.0
8,-cigarette,dataisugly,4,2020,1.0,0.97,NaN
9,-yung-one-,dataisugly,3,2020,1.0,0.98,NaN

In [2]:
df.dtypes

author          object
subreddit       object
month            int64
year             int64
num_posts      float64
avg_upvote     float64
num_replies    float64
dtype: object

In [3]:
df = df.fillna(0)
df.astype({'num_posts': 'int32','avg_upvote':'int32','num_replies':'int32'}).dtypes

author         object
subreddit      object
month           int64
year            int64
num_posts       int32
avg_upvote      int32
num_replies     int32
dtype: object

In [4]:
is_subreddit=df['subreddit']=='visualization'

In [5]:
df_subreddit = df[is_subreddit]
# df_subreddit = df
df_subreddit
df_subreddit.to_csv('visualization.csv', index=False)

In [6]:
df_col = df_subreddit["num_replies"]
df_col.max()

9.0

In [7]:
df_subreddit=df_subreddit[df_subreddit["year"]==2020]
df_subreddit

,author,subreddit,month,year,num_posts,avg_upvote,num_replies
11,060909,visualization,12,2020,0.0,0.00,1.0
20,123ankit321,visualization,12,2020,0.0,0.00,1.0
27,1GoodWoman,visualization,12,2020,0.0,0.00,1.0
39,3M1l4,visualization,3,2020,1.0,0.95,0.0
49,8329417966,visualization,8,2020,1.0,0.81,0.0
...,...,...,...,...,...,...,...
4915,yelper,visualization,12,2020,0.0,0.00,1.0
4917,yinyangyinyang,visualization,12,2020,0.0,0.00,1.0
4919,yoetz,visualization,5,2020,1.0,0.89,0.0
4938,yvthousands,visualization,4,2020,1.0,0.91,0.0
4944,zandikar,visualization,11,2020,0.0,0.00,1.0